ktor:
  deployment:
    development: true
    port: 8080
  application:
    modules:
      - com.wire.aves.server.ApplicationKt.module

jwt:
  secret: "ZwZAfnq2qXaOc1VUuOpcdNimACZAfLv6GaOcIhU9OpcDmi"
  issuer: "https://aves.com"
  realm: "aves-backend-services"